//
//  DisplayOrderPresenter.swift
//  CleanStore
//
//  Created by iMeraj-MacbookPro on 28/12/2017.
//  Copyright (c) 2017 Meraj. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayOrderPresentationLogic
{
  func presentSomething(response: DisplayOrderModel.DTO.Response)
}

class DisplayOrderPresenter: DisplayOrderPresentationLogic
{
  weak var viewController: DisplayOrderDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DisplayOrderModel.DTO.Response)
  {
    let viewModel = DisplayOrderModel.DTO.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
