//
//  DisplayOrderInteractor.swift
//  CleanStore
//
//  Created by iMeraj-MacbookPro on 28/12/2017.
//  Copyright (c) 2017 Meraj. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayOrderBusinessLogic
{
    func doSomething(request: DisplayOrderModel.DTO.Request)
}

protocol DisplayOrderDataStore
{
    var name: String { get set }
}

class DisplayOrderInteractor: DisplayOrderBusinessLogic, DisplayOrderDataStore
{
    var name: String = ""

    var presenter: DisplayOrderPresentationLogic?
    var worker: DisplayOrderWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: DisplayOrderModel.DTO.Request)
    {
        worker = DisplayOrderWorker()
        worker?.doSomeWork()
        
        let response = DisplayOrderModel.DTO.Response()
        presenter?.presentSomething(response: response)
    }
}
