//
//  DisplayOrderViewController.swift
//  CleanStore
//
//  Created by iMeraj-MacbookPro on 28/12/2017.
//  Copyright (c) 2017 Meraj. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayOrderDisplayLogic: class
{
    func displaySomething(viewModel: DisplayOrderModel.DTO.ViewModel)
}

class DisplayOrderViewController: UIViewController, DisplayOrderDisplayLogic
{
    @IBOutlet weak var orderDisplayLabel: UILabel!

    var interactor: DisplayOrderBusinessLogic?
    var router: (NSObjectProtocol & DisplayOrderRoutingLogic & DisplayOrderDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = DisplayOrderInteractor()
        let presenter = DisplayOrderPresenter()
        let router = DisplayOrderRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        orderDisplayLabel.text! = (router?.dataStore?.name)!
        
        //doSomething()
    }
    
    // MARK: Do something
    
    func getOrder() {
        
    }
    
    func doSomething()
    {
        let request = DisplayOrderModel.DTO.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: DisplayOrderModel.DTO.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
