//
//  CreateOrderInteractor.swift
//  CleanStore
//
//  Created by iMeraj-MacbookPro on 28/12/2017.
//  Copyright (c) 2017 Meraj. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol CreateOrderBusinessLogic {
    var createOrderResponse: PublishSubject<CreateOrderModel.DTO.Response> { get set }
    func createOrder(request: CreateOrderModel.DTO.Request)
}

protocol CreateOrderDataStore {
    var name: String { get set }
}

class CreateOrderInteractor: CreateOrderBusinessLogic, CreateOrderDataStore {
    var name: String = ""
    var createOrderResponse = PublishSubject<CreateOrderModel.DTO.Response>()
    
    var presenter: CreateOrderPresentationLogic!
    var worker: CreateOrderWorker!
    
    // MARK: Do something
    func createOrder(request: CreateOrderModel.DTO.Request) {
        worker = CreateOrderWorker(request: request)
        let order = worker.createOrder()
        name = order
        createOrderResponse.onNext(CreateOrderModel.DTO.Response(result: order))
    }
}
