//
//  CreateOrderRouter.swift
//  CleanStore
//
//  Created by iMeraj-MacbookPro on 28/12/2017.
//  Copyright (c) 2017 Meraj. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateOrderRoutingLogic
{
    func routeToDisplayOrder(segue: UIStoryboardSegue?)
}

protocol CreateOrderDataPassing
{
    var dataStore: CreateOrderDataStore? { get }
}

class CreateOrderRouter: NSObject, CreateOrderRoutingLogic, CreateOrderDataPassing
{
    weak var viewController: CreateOrderViewController?
    var dataStore: CreateOrderDataStore?
    
    // MARK: Routing
    
    func routeToDisplayOrder(segue: UIStoryboardSegue?) {
      if let segue = segue {
        let destinationVC = segue.destination as! DisplayOrderViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDisplayOrder(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        var destinationVC = storyboard.instantiateViewController(withIdentifier: "DisplayOrderViewController") as! DisplayOrderViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDisplayOrder(source: dataStore!, destination: &destinationDS)
        navigateToDisplayOrder(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToDisplayOrder(source: CreateOrderViewController, destination: DisplayOrderViewController)
    {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDisplayOrder(source: CreateOrderDataStore, destination: inout DisplayOrderDataStore)
    {
      destination.name = source.name
    }
}
