//
//  CreateOrderViewController.swift
//  CleanStore
//
//  Created by iMeraj-MacbookPro on 28/12/2017.
//  Copyright (c) 2017 Meraj. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderDisplayLogic: class
{
    func displayOrder(viewModel: CreateOrderModel.DTO.ViewModel)
}

class CreateOrderViewController: UITableViewController, CreateOrderDisplayLogic
{
    @IBOutlet weak var firstNameField: UITextField!
    @IBOutlet weak var lastNameField: UITextField!
    
    var interactor: CreateOrderBusinessLogic?
    var router: (NSObject & CreateOrderRoutingLogic & CreateOrderDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = CreateOrderInteractor()
        let presenter = CreateOrderPresenter()
        let router = CreateOrderRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad(){
        super.viewDidLoad()
    }
    
    // MARK: Do something
    
    @IBAction func donePressed(_ sender: Any) {
        createOrder()
    }
    
    func createOrder() {
        let firstName =  firstNameField.text!
        let lastName = lastNameField.text!
        
        let request = CreateOrderModel.DTO.Request(firstName: firstName, lastName: lastName)
        interactor?.createOrder(request: request)
    }
    
    func displayOrder(viewModel: CreateOrderModel.DTO.ViewModel) {
        router?.routeToDisplayOrder(segue: nil)
//        let alertController = UIAlertController(title: "CreateOrder", message: viewModel.formattedResult, preferredStyle: .alert)
//        let alertAction = UIAlertAction(title: "OK", style: .default, handler: nil)
//        alertController.addAction(alertAction)
//        self.present(alertController, animated: true, completion: nil)
    }
}
