//
//  CreateOrderPresenter.swift
//  CleanStore
//
//  Created by iMeraj-MacbookPro on 28/12/2017.
//  Copyright (c) 2017 Meraj. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderPresentationLogic
{
    func presentOrder(response: CreateOrderModel.DTO.Response)
}

class CreateOrderPresenter: CreateOrderPresentationLogic
{
    weak var viewController: CreateOrderDisplayLogic?
    
    // MARK: Do something
    
    func presentOrder(response: CreateOrderModel.DTO.Response)
    {
        let viewModel = CreateOrderModel.DTO.ViewModel(formattedResult: response.result.uppercased())
        viewController?.displayOrder(viewModel: viewModel)
    }
}
