//
//  CreateOrderWorker.swift
//  CleanStore
//
//  Created by iMeraj-MacbookPro on 28/12/2017.
//  Copyright (c) 2017 Meraj. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CreateOrderWorker
{
    var request : CreateOrderModel.DTO.Request?
    
    init(request: CreateOrderModel.DTO.Request?) {
        self.request = request
    }
    
    func createOrder() -> String {
        return "Order created with name: \(request?.firstName ?? "Dummy")"
    }
}
